### ISSUE TITLE
[Interview Session Frontend] Set up interview session additional frontend functionalities

### ISSUE THREAD

**Issue by mirozo** [CS3219-SE-Principles-and-Patterns/cs3219-project-ay2122-2122-s1-g15#26]
F4.9 (M) - When a matched peer leaves the session, the application should notify the other user remaining in the session that the peer has left the session.

F4.10 (M) - The application should allow users to change the question without ending the session.

F4.13 (L) - The application should provide a stopwatch on the session page that users can set, start, pause and reset.

**Comment by liawsy** [comment]
F4.9 done
